# Generated by Django 5.1.15 on 2026-06-04 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('page_url', models.URLField(verbose_name='URL страницы')),
                ('variant_a', models.TextField(verbose_name='Вариант A')),
                ('variant_b', models.TextField(verbose_name='Вариант B')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('a_views', models.IntegerField(default=0, verbose_name='Просмотров A')),
                ('b_views', models.IntegerField(default=0, verbose_name='Просмотров B')),
                ('a_conversions', models.IntegerField(default=0, verbose_name='Конверсий A')),
                ('b_conversions', models.IntegerField(default=0, verbose_name='Конверсий B')),
            ],
            options={
                'verbose_name': 'A/B тест',
                'verbose_name_plural': 'A/B тесты',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('event_type', models.CharField(choices=[('page_view', 'Просмотр страницы'), ('form_submit', 'Отправка формы'), ('click', 'Клик'), ('call', 'Звонок')], max_length=20, verbose_name='Тип события')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('referrer', models.URLField(blank=True, verbose_name='Откуда пришел')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('campaign_type', models.CharField(choices=[('context', 'Контекстная реклама'), ('social', 'Социальные сети'), ('email', 'E-mail рассылка'), ('seo', 'SEO'), ('offline', 'Оффлайн')], max_length=20, verbose_name='Тип кампании')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Потрачено')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Контентная страница',
                'verbose_name_plural': 'Контентные страницы',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('keyword', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция в выдаче')),
                ('volume', models.IntegerField(default=0, verbose_name='Частотность')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
            ],
            options={
                'verbose_name': 'SEO-ключевое слово',
                'verbose_name_plural': 'SEO-ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('appointed', 'Записан'), ('visited', 'Посетил'), ('lost', 'Потерян')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('social', 'Соцсети'), ('call', 'Звонок'), ('referral', 'Рекомендация')], max_length=20, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('recipient_list', models.TextField(help_text='Email через запятую', verbose_name='Список получателей')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланирована на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена')], default='draft', max_length=20, verbose_name='Статус')),
                ('opened_count', models.IntegerField(default=0, verbose_name='Открыто')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='Переходов')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.emailtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
