#!/usr/bin/env python3
"""Generate the rest of the content plan file - version 2."""
# Using only safe strings to avoid truncation

import os

lines = []

# Part 1: Complete the 10.06 section
lines.append(' Апекс. Почему? Потому что он продолжает работу пилинга дома.')
lines.append('')
lines.append('[0:15-0:25] Ряховская показывает крем')
lines.append('"Крем Апекс содержит активные компоненты, которые усиливают и пролонгируют эффект процедуры."')
lines.append('')
lines.append('[0:25-0:35] Ряховская в кадре')
lines.append('"Купить крем можно у нас. А записаться на пилинг — по ссылке в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Пилинг Апекс + крем Апекс = идеальная формула обновления ✨')
lines.append('')
lines.append('Почему важно использовать крем после пилинга?')
lines.append('🧴 Он продолжает работу пилинга')
lines.append('🧴 Защищает кожу после процедуры')
lines.append('🧴 Усиливает результат')
lines.append('')
lines.append('Приходите на пилинг Апекс в ARclinic — и забирайте крем для домашнего ухода.')
lines.append('')
lines.append('Запись — в шапке профиля 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #пилинг #пилингапекс #уходзалицом')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')

# Write the file
with open('content_plan_rest.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'Written {len(lines)} lines to content_plan_rest.md')
lines.append('---')
lines.append('')

# Write the file
with open('content_plan_rest.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'Written {len(lines)} lines to content_plan_rest.md')
lines.append('### 🔹 Текстовый пост (18:00) — Полезный пост «Как ухаживать за кожей после пилинга»')
lines.append('')
lines.append('**Формат:** Карусель (5 слайдов)')
lines.append('**Врач:** Ряховская')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "5 правил ухода после пилинга"')
lines.append('')
lines.append('Слайд 2:')
lines.append('Правило 1: "Использовать крем Апекс"')
lines.append('"Он продолжает работу пилинга и защищает кожу. Наносить 2 раза в день"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Правило 2: "SPF — обязательно!"')
lines.append('"После пилинга кожа особенно чувствительна к солнцу. SPF 50+ каждый день"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Правило 3: "Не использовать агрессивную косметику"')
lines.append('"Никаких скрабов, спиртовых тоников и кислот в первую неделю"')
lines.append('')
lines.append('Слайд 5:')
lines.append('Правило 4: "Не трогать шелушения"')
lines.append('"Кожа обновляется — это нормально. Не сдирайте, дайте ей отойти самой"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Сделали пилинг? Рассказываем, как ухаживать за кожей после процедуры 📝')
lines.append('')
lines.append('Правильный уход — это 50% успеха. Сохраняйте пост, чтобы не забыть 🫶')
lines.append('')
lines.append('А записаться на пилинг Апекс можно по ссылке в шапке профиля.')
lines.append('')
lines.append('#arclinic #арклиникспб #пилинг #уходпослепилинга #советыкосметолога')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 11.06 (ЧТ) — Знакомство с врачом: Подольникова')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Подольникова: о себе и любимых процедурах»')
lines.append('')
lines.append('**Врач:** Подольникова')
lines.append('**Длительность:** 0:35')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Подольникова в кадре, улыбается')
lines.append('"Меня зовут Подольникова, я врач-косметолог в ARclinic. Сегодня расскажу о себе."')
lines.append('')
lines.append('[0:08-0:20] Подольникова продолжает')
lines.append('"В медицину пришла осознанно. Косметология — это идеальный баланс между медициной и эстетикой."')
lines.append('')
lines.append('[0:20-0:30] Кадры: врач проводит процедуру')
lines.append('"Моя любимая процедура — лазерная косметология. Результат виден сразу. Пациентка смотрит в зеркало и говорит Вау!"')
lines.append('')
lines.append('[0:30-0:35] Подольникова в кадре')
lines.append('"До 5 июля — скидка на первую консультацию. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Знакомьтесь — Подольникова, наш врач-косметолог 🤍')
lines.append('')
lines.append('Опыт — 8 лет. Специализация — лазерная косметология, пилинги, уходовые процедуры.')
lines.append('')
lines.append('Подольникова уверена: красивая кожа — это результат грамотного ухода и своевременных процедур.')
lines.append('')
lines.append('До 5 июля — скидка на первую консультацию 🎉')
lines.append('')
lines.append('Запись — в шапке профиля.')
lines.append('')
lines.append('#arclinic #арклиникспб #знакомствосврачом #подольникова #косметолог')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — Полезный пост «Почему я люблю свою работу»')
lines.append('')
lines.append('**Формат:** Текстовый пост + фото врача')
lines.append('**Врач:** Подольникова')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Почему я люблю свою работу? 🫶')
lines.append('')
lines.append('Каждый день я вижу, как меняются женщины. Не только внешне — внутренне.')
lines.append('')
lines.append('Когда пациентка приходит с неуверенностью, прячет лицо за волосами, стесняется улыбаться — а через месяц смотрит в зеркало и говорит: "Я себе нравлюсь".')
lines.append('')
lines.append('Вот ради этого я работаю.')
lines.append('')
lines.append('Мы не просто делаем процедуры. Мы возвращаем женщинам радость смотреть на себя в зеркало. И это бесценно.')
lines.append('')
lines.append('Спасибо, что доверяете мне свою красоту 🤍')
lines.append('')
lines.append('Ваша Подольникова')
lines.append('')
lines.append('#arclinic #арклиникспб #подольникова #косметолог #люблюсвоюработу')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 12.06 (ПТ) — Неодимовый лазер')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Неодимовый лазер: удаляем сосуды и пигмент»')
lines.append('')
lines.append('**Врач:** Подольникова')
lines.append('**Длительность:** 0:30')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:05] Подольникова в кадре, показывает аппликатор')
lines.append('"Неодимовый лазер — золотой стандарт удаления сосудистых дефектов и пигмента."')
lines.append('')
lines.append('[0:05-0:15] Процесс: лазерная вспышка на коже')
lines.append('"Лазер работает точечно: разрушает пигмент и запаивает сосуды, не трогая здоровую кожу."')
lines.append('')
lines.append('[0:15-0:25] Подольникова показывает фото "до" и "после"')
lines.append('"Результат — после первой процедуры. Без реабилитации, без рубцов."')
lines.append('')
lines.append('[0:25-0:30] Подольникова в кадре')
lines.append('"Запись на лазер — по ссылке в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Сосудистая сетка и пигментация — не навсегда ✨')
lines.append('')
lines.append('Неодимовый лазер:')
lines.append('🔸 Убирает купероз и сосудистые звёздочки')
lines.append('🔸 Удаляет пигментные пятна')
lines.append('🔸 Не повреждает здоровую кожу')
lines.append('🔸 Без реабилитации')
lines.append('')
lines.append('Результат — после первой процедуры.')
lines.append('')
lines.append('Запись в ARclinic 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #неодимовыйлазер #лазернаякосметология #купероз')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — До/После «Неодимовый лазер»')
lines.append('')
lines.append('**Формат:** Карусель (4 слайда)')
lines.append('**Врач:** Подольникова')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "Неодимовый лазер. ДО и ПОСЛЕ"')
lines.append('Фото: сосудистая сетка на лице (крупно)')
lines.append('')
lines.append('Слайд 2:')
lines.append('Фото: процесс процедуры')
lines.append('Текст: "Лазерная вспышка длится доли секунды. Ощущение — щипок"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Фото: результат через 2 недели')
lines.append('Текст: "Сосуды закрылись. Кожа чистая, ровная"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Текст: "Курс: 2-4 процедуры с интервалом 3-4 недели.')
lines.append('Запись — в шапке профиля"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('ДО — сосудистая сетка, которую не скрыть тоналкой.')
lines.append('ПОСЛЕ — чистая, ровная кожа ✨')
lines.append('')
lines.append('Неодимовый лазер решает проблему купероза быстро и безболезненно.')
lines.append('')
lines.append('Запись в ARclinic 💫')
lines.append('')
lines.append('#arclinic #арклиникспб #неодимовыйлазер #допосле #купероз')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 13.06 (СБ) — Как выбрать косметолога')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Как выбрать косметолога: 5 правил»')
lines.append('')
lines.append('**Врач:** Ряховская')
lines.append('**Длительность:** 0:40')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Ряховская в кадре')
lines.append('"Как выбрать косметолога и не пожалеть? Делюсь правилами."')
lines.append('')
lines.append('[0:08-0:18] Правило 1')
lines.append('"Первое — образование. Врач должен иметь медицинское образование. Не эстетист, а именно врач."')
lines.append('')
lines.append('[0:18-0:28] Правило 2')
lines.append('"Второе — специализация. Не берите ботокс у лазерщика, а пилинг — у специалиста по инъекциям."')
lines.append('')
lines.append('[0:28-0:40] Правило 3')
lines.append('"Третье — портфолио. Врач должен показать реальные фото до и после. Не из интернета, а свои работы. Остальные правила — в вечернем посте. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Как выбрать косметолога и не пожалеть? 🤔')
lines.append('')
lines.append('5 правил от Ряховской:')
lines.append('1️⃣ Медицинское образование')
lines.append('2️⃣ Узкая специализация')
lines.append('3️⃣ Прозрачность (объясняет риски)')
lines.append('4️⃣ Реальное портфолио')
lines.append('5️⃣ Личная симпатия (вам должно быть комфортно)')
lines.append('')
lines.append('В ARclinic работают врачи с опытом от 7 лет. Каждый — эксперт в своём направлении.')
lines.append('')
lines.append('Запись — в шапке профиля 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #каквыбратькосметолога #советы #ряховская')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — Чек-лист «Как выбрать косметолога»')
lines.append('')
lines.append('**Формат:** Карусель (6 слайдов)')
lines.append('**Врач:** Ряховская')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "Чек-лист: как выбрать косметолога"')
lines.append('')
lines.append('Слайд 2:')
lines.append('Правило 1: "Образование и сертификаты"')
lines.append('"Проверяйте диплом, сертификаты по инъекциям, аппаратной косметологии"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Правило 2: "Специализация"')
lines.append('"Один врач не может быть экспертом во всём. Выбирайте по профилю"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Правило 3: "Прозрачность"')
lines.append('"Врач должен объяснить риски, противопоказания и альтернативы"')
lines.append('')
lines.append('Слайд 5:')
lines.append('Правило 4: "Портфолио"')
lines.append('"Реальные фото до/после — лучший показатель работы"')
lines.append('')
lines.append('Слайд 6:')
lines.append('Правило 5: "Комфорт"')
lines.append('"Вам должно быть комфортно с врачом. Доверие — основа результата"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Сохраняйте этот чек-лист — пригодится при выборе косметолога 📌')
lines.append('')
lines.append('В ARclinic все наши врачи соответствуют этим критериям. Приходите — убедитесь сами 🌸')
lines.append('')
lines.append('Запись — в шапке профиля.')
lines.append('')
lines.append('#arclinic #арклиникспб #каквыбратькосметолога #чеклист #советы')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 14.06 (ВС) — Микроколлост')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Микроколлост: плазмотерапия нового поколения»')
lines.append('')
lines.append('**Врач:** Батиенко')
lines.append('**Длительность:** 0:35')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Батиенко в кадре')
lines.append('"Микроколлост — это не просто плазмотерапия. Это регенерация кожи на новом уровне."')
lines.append('')
lines.append('[0:08-0:20] Процесс: забор крови, центрифуга')
lines.append('"Из вашей крови выделяются факторы роста, которые запускают мощное восстановление кожи."')
lines.append('')
lines.append('[0:20-0:30] Батиенко продолжает')
lines.append('"Стимулирует выработку коллагена, эластина и гиалуроновой кислоты. Кожа обновляется изнутри."')
lines.append('')
lines.append('[0:30-0:35] Батиенко')
lines.append('"Курс — 3 процедуры с интервалом 2 недели. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Микроколлост — плазмотерапия, которая реально работает ✨')
lines.append('')
lines.append('В чём отличие от обычной плазмотерапии?')
lines.append('🧬 Высокая концентрация факторов роста')
lines.append('🧬 Стимуляция собственного коллагена')
lines.append('🧬 Омоложение изнутри')
lines.append('')
lines.append('Курс 3 процедуры — и кожа обновляется.')
lines.append('')
lines.append('Запись в ARclinic 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #микроколлост #плазмотерапия #омоложение')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — До/После «Микроколлост»')
lines.append('')
lines.append('**Формат:** Карусель (4 слайда)')
lines.append('**Врач:** Батиенко')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "Микроколлост. ДО и ПОСЛЕ курса"')
lines.append('Фото: тусклая кожа, морщины, неровный рельеф')
lines.append('')
lines.append('Слайд 2:')
lines.append('Фото: процесс процедуры')
lines.append('Текст: "Забор крови → центрифуга → введение. Процедура — 40 минут"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Фото: результат после курса')
lines.append('Текст: "Кожа упругая, сияющая. Морщины разглажены"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Текст: "Курс: 3 процедуры с интервалом 2 недели.')
lines.append('Эффект — до 12 месяцев.')
lines.append('Запись — в шапке профиля"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Обновление кожи изнутри — это возможно ✨')
lines.append('')
lines.append('Микроколлост запускает собственные механизмы омоложения. Без химии, без филлеров — только ваша кровь и её ресурсы.')
lines.append('')
lines.append('Результат — на фото.')
lines.append('')
lines.append('Запись в ARclinic 💫')
lines.append('')
lines.append('#arclinic #арклиникспб #микроколлост #допосле #плазмотерапия')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('# 📅 НЕДЕЛЯ 3 (15.06 — 21.06)')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 15.06 (ПН) — Подольникова (продолжение)')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Почему я люблю свою работу»')
lines.append('')
lines.append('**Врач:** Подольникова')
lines.append('**Длительность:** 0:30')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Подольникова улыбается в кадре')
lines.append('"Самое приятное в моей работе — момент, когда пациентка смотрит в зеркало и говорит: Вау! Это я?"')
lines.append('')
lines.append('[0:08-0:20] Подольникова продолжает')
lines.append('"Мы не просто делаем процедуры. Мы возвращаем женщинам уверенность. Когда ты нравишься себе — ты светишься по-другому."')
lines.append('')
lines.append('[0:20-0:30] Подольникова')
lines.append('"Каждая женщина заслуживает выглядеть и чувствовать себя прекрасно. В любом возрасте. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('"Самое приятное — когда пациентка смотрит в зеркало и говорит Вау!" 🫶')
lines.append('')
lines.append('Подольникова — о своей работе, о женщинах и о том, почему красота — это про уверенность.')
lines.append('')
lines.append('А что вас беспокоит? Поделитесь в комментариях 💬')
lines.append('')
lines.append('Запись к Подольниковой — в шапке профиля.')
lines.append('')
lines.append('#arclinic #арклиникспб #подольникова #косметолог #искренность')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — Полезный пост «3 процедуры для сияния кожи»')
lines.append('')
lines.append('**Формат:** Карусель (4 слайда)')
lines.append('**Врач:** Подольникова')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "3 процедуры для сияющей кожи от Подольниковой"')
lines.append('')
lines.append('Слайд 2:')
lines.append('Процедура 1: "БРВ (биоревитализация)"')
lines.append('"Глубинное увлажнение гиалуроновой кислотой. Курс 3 процедуры"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Процедура 2: "Микроколлост"')
lines.append('"Плазмотерапия нового поколения. Запускает регенерацию"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Процедура 3: "Фототерапия"')
lines.append('"Выравнивает тон, убирает пигмент и сосуды. Без инъекций"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Хотите сияющую кожу? Вот 3 процедуры, которые реально работают ✨')
lines.append('')
lines.append('Каждая решает свою задачу. А вместе — дают потрясающий результат.')
lines.append('')
lines.append('Приходите на консультацию — Подольникова подберёт идеальный протокол для вас 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #процедурыдлялица #сияниекожи #подольникова')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 16.06 (ВТ) — Айкун')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Айкун: аппаратная косметология без боли»')
lines.append('')
lines.append('**Врач:** Дежурный косметолог')
lines.append('**Длительность:** 0:30')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Кадр: аппарат Айкун в работе на лице пациентки')
lines.append('Голос за кадром: "Айкун — аппаратная косметология без боли, без уколов, без реабилитации."')
lines.append('')
lines.append('[0:08-0:20] Крупный план: микротоки + LED-терапия')
lines.append('"Микротоки стимулируют мышцы лица, LED-терапия запускает восстановление кожи."')
lines.append('')
lines.append('[0:20-0:30] Врач в кадре')
lines.append('"Можно делать в обед. После процедуры — сразу на работу. Никаких следов. Курс 8-10 процедур. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Айкун — аппаратная косметология для тех, кто боится уколов ✨')
lines.append('')
lines.append('Что делает процедура:')
lines.append('💫 Микротоки — лифтинг мышц лица')
lines.append('💫 LED-терапия — восстановление кожи')
lines.append('💫 Без боли, без реабилитации')
lines.append('')
lines.append('Курс 8-10 процедур — и вы выглядите отдохнувшей.')
lines.append('')
lines.append('Идеально для поддержания результата после инъекций.')
lines.append('')
lines.append('Запись — в шапке профиля 🌸')
lines.append('')
lines.append('#arclinic #арклиникспб #айкун #аппаратнаякосметология #микротоки')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — До/После «Айкун»')
lines.append('')
lines.append('**Формат:** Карусель (4 слайда)')
lines.append('**Врач:** Дежурный косметолог')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "Айкун. ДО и ПОСЛЕ курса"')
lines.append('Фото: уставшая кожа, тусклый цвет, мелкие морщины')
lines.append('')
lines.append('Слайд 2:')
lines.append('Фото: процесс процедуры')
lines.append('Текст: "Микротоки + LED. Процедура — 30 минут. Ощущение — приятное тепло"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Фото: результат после курса')
lines.append('Текст: "Свежая, отдохнувшая кожа. Лицо подтянуто"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Текст: "Курс: 8-10 процедур, 2 раза в неделю.')
lines.append('Рекомендуем 1 раз в 3 месяца для поддержания.')
lines.append('Запись — в шапке профиля"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Устали от тусклой кожи? Айкун вернёт сияние без уколов ✨')
lines.append('')
lines.append('Курс процедур — и вы забываете о тоналке. Кожа светится изнутри.')
lines.append('')
lines.append('Запись в ARclinic 💫')
lines.append('')
lines.append('#arclinic #арклиникспб #айкун #допосле #аппаратнаякосметология')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('## 17.06 (СР) — Менопауза и её симптомы')
lines.append('')
lines.append('### 🔹 Reels (10:00) — «Менопаузу можно отодвинуть?»')
lines.append('')
lines.append('**Врач:** Афанасьева')
lines.append('**Длительность:** 0:35')
lines.append('')
lines.append('**Сценарий:**')
lines.append('```')
lines.append('[0:00-0:08] Афанасьева в кадре')
lines.append('"Менопауза — не болезнь. Но её симптомы можно и нужно корректировать."')
lines.append('')
lines.append('[0:08-0:20] Афанасьева продолжает')
lines.append('"Приливы, бессонница, сухость кожи, снижение либидо — это не возрастное. Это гормональные изменения, которые решаются."')
lines.append('')
lines.append('[0:20-0:30] Афанасьева')
lines.append('"Современная медицина позволяет отодвинуть симптомы менопаузы на 5-10 лет. ЗГТ, коррекция образа жизни, косметология — комплексный подход."')
lines.append('')
lines.append('[0:30-0:35] Афанасьева')
lines.append('"Не нужно терпеть. Приходите — мы поможем. Запись — в шапке профиля."')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('Менопаузу и её симптомы можно отодвинуть. Это не миф, а факт ✅')
lines.append('')
lines.append('Гинеколог Афанасьева рассказывает, как современная медицина помогает женщинам оставаться активными и здоровыми.')
lines.append('')
lines.append('В ARclinic — комплексный подход к женскому здоровью:')
lines.append('🌸 Гинекология')
lines.append('🌸 Эндокринология')
lines.append('🌸 Косметология')
lines.append('')
lines.append('Запись — в шапке профиля 🤍')
lines.append('')
lines.append('#arclinic #арклиникспб #менопауза #згт #гинеколог')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
lines.append('### 🔹 Текстовый пост (18:00) — Полезный пост «5 симптомов менопаузы»')
lines.append('')
lines.append('**Формат:** Карусель (6 слайдов)')
lines.append('**Врач:** Афанасьева')
lines.append('')
lines.append('**Сценарий слайдов:**')
lines.append('```')
lines.append('Слайд 1:')
lines.append('Заголовок: "5 симптомов менопаузы, которые можно отсрочить"')
lines.append('')
lines.append('Слайд 2:')
lines.append('Симптом 1: "Приливы"')
lines.append('Решение: "Коррекция образа жизни + ЗГТ под контролем врача"')
lines.append('')
lines.append('Слайд 3:')
lines.append('Симптом 2: "Сухость кожи"')
lines.append('Решение: "Косметология (БРВ, фототерапия) + увлажняющий уход"')
lines.append('')
lines.append('Слайд 4:')
lines.append('Симптом 3: "Нарушение сна"')
lines.append('Решение: "Мелатонин, режим, снижение стресса"')
lines.append('')
lines.append('Слайд 5:')
lines.append('Симптом 4: "Снижение либидо"')
lines.append('Решение: "Гинеколог + эндокринолог — ищем причину и корректируем"')
lines.append('')
lines.append('Слайд 6:')
lines.append('Симптом 5: "Набор веса"')
lines.append('Решение: "ЗГТ + диетолог + физическая активность"')
lines.append('```')
lines.append('')
lines.append('**Текст для подписи:**')
lines.append('```')
lines.append('5 симптомов менопаузы, которые не нужно терпеть 🚫')
lines.append('')
lines.append('Каждый из них решается современной медициной. Вы не одни — мы рядом.')
lines.append('')
lines.append('Запись к гинекологу ARclinic 🤍')
lines.append('')
lines.append('#arclinic #арклиникспб #менопауза #симптомыменопаузы #гинеколог')
lines.append('```')
lines.append('')
lines.append('---')
lines.append('')
